name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v3

      # 2) -------- 手動ビルド (devDependencies を含む) --------
      - name: Install & Build
        run: |
          cd app
          npm ci
          npm run build            # → app/dist に index.html 生成

      # 3) -------- dist をサイトルートとしてアップロード --------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_TREE_01078A410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # ---------- 重要設定 ----------
          app_location: "app/dist"                 # dist をサイトルートに
          skip_app_build: true                     # Oryx ビルドを完全スキップ
          api_location: ""                         # API なし
          skip_api_build: true
          routes_location: "app/staticwebapp.config.json"   # ★ SPA リライトルールを明示
          # ----------------------------------

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Preview Env
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_TREE_01078A410 }}
          action: close
